[package]
name = "plotty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ab_glyph = "0.2.21"
softbuffer = "0.3.0"
winit = "0.28.6"
